name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
            personal_token: ${{ secrets.TOKEN }}
            external_repository: repopage/repopage.github.io
            publish_branch: main  # default: gh-pages
            publish_dir: ./src/public
            destination_dir: destinationdir